# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy

on:
  schedule:
    - cron: "5,20,35,50 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Hong_Kong"

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache yarn dependencies
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-

    - run: yarn install --immutable
    - run: yarn run crawl
    - name: Update resources
      uses: JamesIves/github-pages-deploy-action@v4.6.4
      with:
        branch: data # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
        clean: false
        single-commit: true
    - run: yarn run precompute
    - name: Update cache
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: cache # The branch the action should deploy to.
        folder: precompute # The folder the action should deploy.
        clean: true
        single-commit: true
